fix build for Node.js 5.x
For some very weird reason the buster-test command behaves a bit
different on Node.js 5.x and the additional command line argument
"test" filters away all tests so the npm test and npm coverage end in
some unintelligible error:

Uncaught exception in Unknown context:

  Error: No contexts
    Error: No contexts
          at Object.bane.createEventEmitter.runSuite (/home/bastian/projekte/repoman/node_modules/buster-test/lib/test-runner.js:477:47)
          at Function.autoRun.run (/home/bastian/projekte/repoman/node_modules/buster-test/lib/auto-run.js:142:16)
          at null._onTimeout (/home/bastian/projekte/repoman/node_modules/buster-test/lib/auto-run.js:70:29)
          at Timer.listOnTimeout (timers.js:92:15)